let books=JSON.parse(localStorage.getItem('books')||'[]'),students=JSON.parse(localStorage.getItem('students')||'[]'),loans=JSON.parse(localStorage.getItem('loans')||'[]');
const $=id=>document.getElementById(id), save=()=>{localStorage.setItem('books',JSON.stringify(books));localStorage.setItem('students',JSON.stringify(students));localStorage.setItem('loans',JSON.stringify(loans));render()};
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(b.dataset.page).classList.add('active');$('menu').classList.remove('open');render()});$('menuBtn').onclick=()=>$('menu').classList.toggle('open');
function openForm(x){$(x).showModal()}function closeForm(x){$(x).close()}
function saveBook(e){e.preventDefault();books.push({id:Date.now(),qr:'BK-'+String(books.length+1).padStart(6,'0'),name:$('bName').value,author:$('bAuthor').value,type:$('bType').value,cab:$('bCab').value,shelf:$('bShelf').value,order:$('bOrder').value});e.target.reset();closeForm('bookForm');save()}
function saveStudent(e){e.preventDefault();students.push({id:Date.now(),name:$('sName').value,cls:$('sClass').value,branch:$('sBranch').value,no:$('sNo').value});e.target.reset();closeForm('studentForm');save()}
function lendBook(){let book=+$('loanBook').value,student=+$('loanStudent').value,due=$('dueDate').value;if(!book||!student||!due)return alert('Kitap, öğrenci ve son teslim tarihini seç.');loans.push({id:Date.now(),book,student,start:new Date().toISOString().slice(0,10),due,returned:null});save()}
function returnBook(id){let l=loans.find(x=>x.id===id);if(l){l.returned=new Date().toISOString().slice(0,10);save()}}
function delBook(id){if(confirm('Bu kitap silinsin mi?')){books=books.filter(x=>x.id!==id);save()}}function delStudent(id){if(confirm('Bu öğrenci silinsin mi?')){students=students.filter(x=>x.id!==id);save()}}
function render(){let active=loans.filter(l=>!l.returned),today=new Date().toISOString().slice(0,10),late=active.filter(l=>l.due<today);$('sKitap').textContent=books.length;$('sOgr').textContent=students.length;$('sOdunc').textContent=active.length;$('sGec').textContent=late.length;
$('bookList').innerHTML=books.map(b=>`<div class=item><div><b>${b.name}</b><small>${b.author} · ${b.type||'-'} · ${b.qr} · Dolap ${b.cab||'-'} / Raf ${b.shelf||'-'} / Sıra ${b.order||'-'}</small></div><div class=buttons><button onclick="alert('QR No: ${b.qr}')">QR Kod</button><button class=muted onclick='delBook(${b.id})'>Sil</button></div></div>`).join('')||'<div class=box>Henüz kitap eklenmedi.</div>';
$('studentList').innerHTML=students.map(s=>`<div class=item><div><b>${s.name}</b><small>${s.cls}/${s.branch} · No: ${s.no}</small></div><div class=buttons><button onclick="alert('${active.filter(l=>l.student===s.id).length} ödünç kitap var.')">Ödünç Kitap Bilgisi</button><button class=muted onclick='delStudent(${s.id})'>Sil</button></div></div>`).join('')||'<div class=box>Henüz öğrenci eklenmedi.</div>';
let available=books.filter(b=>!active.some(l=>l.book===b.id));$('loanBook').innerHTML='<option value="">Kitap seçin</option>'+available.map(b=>`<option value=${b.id}>${b.name} (${b.qr})</option>`).join('');$('loanStudent').innerHTML='<option value="">Öğrenci seçin</option>'+students.map(s=>`<option value=${s.id}>${s.name} - ${s.no}</option>`).join('');
let loanHTML=active.map(l=>{let b=books.find(x=>x.id===l.book),s=students.find(x=>x.id===l.student);return `<div class=item><div><b>${b?.name||'Kitap'}</b><small>${s?.name||'Öğrenci'} · Ödünç: ${l.start} · Son teslim: ${l.due}</small></div><button onclick='returnBook(${l.id})'>Geri Al</button></div>`}).join('');$('loanList').innerHTML=loanHTML;$('sonIslem').innerHTML=loanHTML||'Henüz işlem yok.';$('lateList').innerHTML=late.map(l=>{let b=books.find(x=>x.id===l.book),s=students.find(x=>x.id===l.student),days=Math.ceil((new Date(today)-new Date(l.due))/86400000);return `<div class=item><div><b>${b?.name}</b><small>${s?.name} · ${l.due} · ${days} gün gecikti</small></div><button onclick='returnBook(${l.id})'>Geri Al</button></div>`}).join('')||'<div class=box>Geciken kitap yok. 🎉</div>'}
$('bookSearch').oninput=e=>{let q=e.target.value.toLocaleLowerCase('tr');document.querySelectorAll('#bookList .item').forEach(x=>x.style.display=x.innerText.toLocaleLowerCase('tr').includes(q)?'flex':'none')};$('studentSearch').oninput=e=>{let q=e.target.value.toLocaleLowerCase('tr');document.querySelectorAll('#studentList .item').forEach(x=>x.style.display=x.innerText.toLocaleLowerCase('tr').includes(q)?'flex':'none')};render();
